version: '3.1'
services:
  php:
    container_name: ${APP_NAME}_php
    build:
      context: .
      dockerfile: php.dockerfile
    restart: on-failure
    expose:
      - 80
    ports:
      - 8003:80
    volumes:
      - ./html:/var/www/html
      - ./logs:/var/log/apache2
      - ./php-conf/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
    networks:
      - nginx_default
  
  db:
    image: mysql:5.7
    restart: on-failure
    container_name: ${APP_NAME}_db
    hostname: ${APP_NAME}_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    ports:
      - 9906:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - nginx_default

networks:
  nginx_default:
    external: true
